# Docker Compose configuration file
#
# References:
#
# * Compose Specification | Compose file reference | Reference | Docker Docs
#   https://docs.docker.com/compose/compose-file/
#
# Copyright 2024 林博仁(Buo-ren, Lin) <Buo.Ren.Lin@gmail.com>
# SPDX-License-Identifier: CC-BY-SA-4.0
version: '3'

name: tesseract-orange
services:
  builder:
    container_name: tesseract-orange-builder
    hostname: tesseract-orange-builder
    image: ubuntu:jammy
    volumes:
      - type: bind
        source: ./
        target: /project
      # For determining the hostname part of the distribution package
      - type: bind
        source: /etc/hostname
        target: /etc/hostname.builder-host
        read_only: true
    command: sleep infinity
    environment:
      - http_proxy
      - https_proxy
      - HTTP_PROXY
      - HTTPS_PROXY

      # Set this environment variable to your local timezone settings
      # for proper operation timestamp
      #- TZ=CST-8
